spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sapi}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: rabbitmq
    password: rabbitmq

ac2:
  rabbitmq:
    exchange: ac2.curso.exchange
    queue:
      ai-recommendation: ac2.curso.ai-recommendation
      dlq: ac2.curso.dlq
    routing-key: ac2.curso.concluido

gemini:
  api-key: ${GEMINI_API_KEY:}
  model: gemini-2.0-flash
  temperature: 0.4

      
     
hikari:
      connection-timeout: 30000  # Tempo de espera para a conexão (em milissegundos)
      maximum-pool-size: 5       # Tamanho máximo do pool de conexões
      max-lifetime: 1800000      # Tempo máximo de vida para uma conexão no pool
      idle-timeout: 600000       # Tempo de inatividade antes de uma conexão ser descartada